version: "3.9"

services:
  eurekaserver:
    #   build: C:\sandbox\microservices\Haythem\EurekaServer
    container_name: eureka
    image: unholyhoper/eureka
    networks:
      - eureka-server
    ports:
      - "8761:8761"

  microservice-users:
    #   build: C:\sandbox\microservices\Haythem\users-management
    container_name: users-management
    image: unholyhoper/users-management
    ports:
      - "8801:8801"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    depends_on:
      - eurekaserver
      - keycloak

  microservice-gateway:
    #   build: C:\sandbox\microservices\Haythem\gateway
    container_name: microservices-microservice-gateway-1
    image: unholyhoper/gateway
    ports:
      - "8762:8762"
    networks:
      - eureka-server
    environment:
      - eureka.client.serviceUrl.defaultZone=http://eureka:8761/eureka
    depends_on:
      - eurekaserver

  keycloak:
    image: f42d810db3c2f27a439a78b3e21b56b1255e639d969a79346ad3b0add608b812
    entrypoint: ["/opt/keycloak/bin/kc.sh", "start"]
    container_name: keycloak
    networks:
      - eureka-server
    ports:
      - "8443:8443"
    environment:
      DB_VENDOR: oracle
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_URL: jdbc:oracle:thin:@host.docker.internal:1521:orcl
      KC_DB: oracle
    volumes:
      - ./microservices-realm.json:/tmp/microservices-realm.json
    depends_on:
      - eurekaserver

#  oracle:
#    image: container-registry.oracle.com/database/free:latest
#    container_name: oracle19c
#    ports:
#      - 1521:1522
#    environment:
#      ORACLE_SID: ORCLCDB
#      ORACLE_PDB: KEYCLOAK
#      ORACLE_PWD: KEYCLOAK
#    volumes:
#      - ./data:/opt/oracle/oradata
#    networks:
#      - eureka-server


networks:
  eureka-server:
    name: eureka-server
    driver: bridge
